apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: timescaledb-pv-claim
  namespace: db
  labels:
    app: timescaledb
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
