apiVersion: v1
kind: Service
metadata:
  name: timescaledb
  namespace: db
spec:
  ports:
  - port: 5432
  selector:
    app: timescaledb
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: timescaledb
  namespace: db
spec:
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
      - image: "timescale/timescaledb:1.0.0-pg10"
        name: timescaledb
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: timescaledb
              key: postgres-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: timescaledb
        volumeMounts:
        - name: timescaledb-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: timescaledb-persistent-storage
        persistentVolumeClaim:
          claimName: timescaledb-pv-claim
